### ISSUE TITLE
Add "no-log" modus to binary

### ISSUE THREAD

**Issue by martinheidegger** [hyperswarm/dht#10]
When starting the dht as a node it will automatically log requests

https://github.com/hyperswarm/dht/blob/153d0fb498cc8ba106e64ba23612e28ee250a447/bin.js#L11-L21

this might fill up the hard disc and it should be possible to switch it of.

_Note: I am not sure how to implement this best, else I would send a PR_

**Comment by davidmarkclements** [comment]
to implement: 

* accept a flag on the command line (e.g. `-q`)
* `const quiet = process.argv.indexOf('-q') > -1`
* every log `if (quiet) console.log('blah')`

**Comment by da2x** [comment]
This was resolved in #28.
