### ISSUE TITLE
Why is the maxSize statically limited?

### ISSUE THREAD

**Issue by martinheidegger** [hyperswarm/dht#12]
The maxSize of the DHT is statically limited to 2^16 nodes. It might mean that more don't make sense? https://github.com/hyperswarm/dht/blob/153d0fb498cc8ba106e64ba23612e28ee250a447/index.js#L22

How much memory is needed/recommended for the current limit?

**Comment by mafintosh** [comment]
it's only your local storage for external records, nothing to do with dht itselfs :)
