### ISSUE TITLE
clarification on bootstrap

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [hyperswarm/dht#20]
Friendly message coming in, sorry for the topic though.

Having traced all modules down to dht-rpc, I find it rather apalling, that we bootstrap against 3 servers on a (privacy protected whois) domain, which does not expose the owner or contents. 

Obviously this makes a DHT rather simple to use, but am I not correct to see this as a major security concern? Right now the topics seem guessable and hence it should be quite difficult to ever employ some permission system on top of it as well.

I suggest at least making that fact VERY VERY public or even rather throw an exception if an implementer does not provide an array or opt into the defaults.

Taking this one step further all related bootstrap properties should probably allow for async functions to allow for a more dynamic and / or multi way discovery, e.g. via DNS and neighbours and then also be able to validate an origin.

Kind regards

**Comment by mafintosh** [comment]
Can you explain why you consider this a security concern?

This is how DHTs operate in general, ie you need an entry point to the network. The bittorrent dht does this, same for the ethereum etc. Nothing fancy happens at the bootstrappers.

You should never implicitly trust any data from a dht for this reason. Thats why you bootstrap trust through other means like we do in the dat stack.

You can of course use your own bootstrapper if you want to.

Normally you need a set per type of network you run, why is why dht-rpc forces you to explicitly pass them in.

For the record it’s me and @pfrazee that runs the current Hyperswarm bootstrap nodes using the dht-rpc-bootstrap module.
