### ISSUE TITLE
What's the difference between mutable and immutable methods put()?

### ISSUE THREAD

**Issue by GildedHonour** [hyperswarm/dht#39]
What's the difference between mutable and immutable methods put()?

**Comment by lanmower** [comment]
Hi there, as far as I understand in p2p tech, if its immutable it gets signed with your nodes privkey, so that others can verify the message came from your node and was unmodified...

**Comment by mafintosh** [comment]
Immutable is "key is the hash", mutable is "key is the public key", the first one is self describing - the second one is updatable but, you might get an older value if the newest one is not found.

**Comment by lanmower** [comment]
Thank you that lends a lot of clarity 🙏
