### ISSUE TITLE
Strange error.

### ISSUE THREAD

**Issue by lanmower** [hyperswarm/dht#49]
att @mafintosh suggested I post here

This is occurring when I leave nodes running for a long time...

![image](https://user-images.githubusercontent.com/657315/126771912-be8661b3-1135-4176-a773-b856bf86fe9b.png)

I have no idea how to collect further information on this issue, but it has happened twice.

**Comment by mafintosh** [comment]
Still trying to repro this one, so let's keep it open for now and if we don't see it the next months we can prob assume it's fixed through one of the recent refactors.
