### ISSUE TITLE
Cache handshake information for quick-connect of additional sockets

### ISSUE THREAD

**Issue by pfrazee** [hyperswarm/dht#56]
Opening this issue per @mafintosh's request

It should be possible to speed up subsequent connections to a peer after the first connection by caching some of the handshake information.

**Comment by lanmower** [comment]
Thank you guys! :) just found the link after following up on all of our earlier discussions

**Comment by jb0gie** [comment]
![FistPumpYeahGIF](https://user-images.githubusercontent.com/6885227/147091329-bc4f9856-3f0e-4cec-8fdf-b6fc3a0dcda6.gif)

**Comment by dnh33** [comment]
Yes please

**Comment by mafintosh** [comment]
Landed now! :) 🚀
