### ISSUE TITLE
README.md encryptedConnection.on('open'), is this a mistake?

### ISSUE THREAD

**Issue by Nazeh** [hyperswarm/dht#69]
In the [readme](https://github.com/hyperswarm/dht#encryptedconnectiononopen) 
```md
encryptedConnection.on('open')
Emitted when the encrypted connection has been fully established with the server.
```

I searched in `hyperswarm/dht` and `secret-stream` I can't see this even omitted, and I don't believe it is inherited from the Duplex either.

**Comment by mafintosh** [comment]
Yep client connections emit open. Part of the streamx state machine

**Comment by mafintosh** [comment]
They also emit “connect” as nodejs tcp compat

**Comment by Nazeh** [comment]
Thanks
