### ISSUE TITLE
implement get and put

### ISSUE THREAD

**Issue by davidmarkclements** [hyperswarm/dht#7]
similar api to bitorrent-dht get/put

needs four dht-rpc commands 

* mutable-get
* mutable-put
* immutable-get
* immutable-put

**Comment by davidmarkclements** [comment]
done!

**Comment by pfrazee** [comment]
Sweet!

**Comment by pfrazee** [comment]
I assume the values have a TTL that require them to be "re-put" right? What's that TTL?

**Comment by davidmarkclements** [comment]
I think they have to be re-put due to reactive topology (e.g. nodes go down and up, k-buckets get rearranged) but there's no enforced TTL

**Comment by pfrazee** [comment]
I'm wondering if we need an enforced TTL to make sure dead values don't collect and fill up nodes' memories

**Comment by davidmarkclements** [comment]
so it uses an LRU which isn't based on TTL but based on max size https://github.com/hyperswarm/dht/blob/master/index.js#L6

**Comment by pfrazee** [comment]
Gotcha, thanks
