### ISSUE TITLE
Node can be connected to by its defaultKeyPair.publicKey, even if `node.listening` is empty.

### ISSUE THREAD

**Issue by Nazeh** [hyperswarm/dht#70]
While testing I realized, I can connect to a node by its defaultKeyPair, even if there are no listening servers (`node1.listening.size === 0`, is that intended behavior? can I expect that to persist in the future, because if so, then I will expect the `defaultKeyPair` to be accessible as well, as a way to pass the node address, without running a server first?

```js
    const node1 = new DHT()
    // const server = node1.createServer();
    // await server.listen();

    const node2 = new DHT()
    const secretSocket = node2.connect(node1.defaultKeyPair.publicKey)

    expect(secretSocket.remotePublicKey).to.eql(node1.defaultKeyPair.publicKey)
    expect(node1.defaultKeyPair.publicKey).to.not.eql(node2.defaultKeyPair.publicKey)
    expect(secretSocket.publicKey).to.eql(node2.defaultKeyPair.publicKey)

    node1.destroy()
    node2.destroy()
```

**Comment by mafintosh** [comment]
Not sure what you mean, can you make a runnable gist to illustrate?

**Comment by Nazeh** [comment]
My band, I mistook the noise connection having the `publicKey` and `remotePublicKey` as a proxy of being correctly opened, but if I wait for `on('open')` without a running server, a `Could not find peer` error is thrown, as expected.
