### ISSUE TITLE
stream from node.lookup() doesn't match the documented interface

### ISSUE THREAD

**Issue by Nazeh** [hyperswarm/dht#72]
Calling `node.lookup` doesn't return the object described here:
https://github.com/hyperswarm/dht#const-stream--nodelookuptopic-options

It returns a `Query` instance from the `dht-rpc` and I can't find the described interface there either.

**Comment by mafintosh** [comment]
Ah the query IS a stream. Use like you would any nodejs stream or async iterator

**Comment by mafintosh** [comment]
The wording could be better, (feel free to improve :)) but the "looks like this" part describes the data returned.

**Comment by Nazeh** [comment]
I couldn't get any chunks with `on('data')`, however this works:
```js
await stream.finished();
stream.closestNodes
```
Which are the public functions on Query, so I will leave it at that until I find a use for any other API.

**Comment by mafintosh** [comment]
It emits data, end, close. If you data was emitted the stream was prob empty.

**Comment by Nazeh** [comment]
Well, how to send data?

All I have is another nod e that is announcing:
```js
      const node = new DHT({ keyPair });
      node.announce(topic);
``

So if that doesn't result in data, I am not sure what does?

**Comment by mafintosh** [comment]
For example this one, https://github.com/hyperswarm/dht/blob/master/test/announces.js#L36-L39

**Comment by Nazeh** [comment]
I didn't wait for the announced stream to finish.

This work fine:
```js
      await node.announce(topic, keyPair).finished();
```
